### ISSUE TITLE
Suggestion: Add install instructions for someone who has never used Node before

### ISSUE THREAD

**Issue by timothyclemansinsea** [timwis/node-soda2-parser#3]

**Comment by timothyclemansinsea** [comment]
Fortunately for me, cloud.sagemath.com has Node already installed.

I did `npm install git+https://git@github.com/timwis/node-soda2-parser.git` Now I gotta figure out to convert the AST to SQL.

**Comment by timwis** [comment]
Good idea. Perhaps an `Installation` section above `Usage` on the readme. Are you up for proposing that in a pull request? You can install it via `npm install node-soda2-parser`

**Comment by timothyclemansinsea** [comment]
Yes I'm proposing putting that in a pull request.
