### ISSUE TITLE
Add a default limit of 1000

### ISSUE THREAD

**Issue by timothyclemansinsea** [timwis/node-soda2-parser#6]
The default $limit on Socrata is 1000. https://dev.socrata.com/docs/queries/

**Comment by timwis** [comment]
Are you suggesting that if `$limit` is not specified, the resulting SQL should _always_ include `LIMIT 1000`? That doesn't seem to fit, unless I'm misunderstanding.

**Comment by timothyclemansinsea** [comment]
Yes. This is the behavior of Socrata's implementation. I got interested in
it because I realized if I didn't add $limit that I was getting all rows.

**Comment by timwis** [comment]
I've opted to do this in the [layer above](https://github.com/timwis/soda-carto/commit/8c28efda9c9ae87dc434d4f280a779bb63ea867d) this one. I can see the argument for it living in node-soda2-parser, but (a) considering it will affect all of the tests of this repo and any layer above it, and (b) considering other providers may warrant an even narrower limit, I think it makes more sense it to leave it at the layer above this for now.
