### ISSUE TITLE
$limit=10 is procuding LIMIT 0,10 instead of LIMIT 10

### ISSUE THREAD

**Issue by timothyclemansinsea** [timwis/node-soda2-parser#7]
I'm getting this error from CartoDB when sending it the result of $select=*&$limit=10 {"error":["LIMIT #,# syntax is not supported"],"hint":"Use separate LIMIT and OFFSET clauses."}

**Comment by timwis** [comment]
Hm, [the code](https://github.com/timwis/node-soda2-parser/blob/master/index.js#L38-L41) suggests it will produce `LIMIT 10` unless you specify an offset, in which case it will produce `LIMIT 10, X`. Although it sounds like you're saying the stringify method is causing the problem?

**Comment by timothyclemansinsea** [comment]
Yea. I fixed it in my fork. I'm almost wondering if this generic parser needs a setting for which SQL implementation you're using as it seems Postgres doesn't use LIMIT 0, 10. There could be other issues as well that need a setting.

**Comment by timwis** [comment]
Fixed and published as major version release since it's a breaking change
